import { readFile, writeFile } from "node:fs/promises";

const coreSource = await readFile(new URL("../assets/core.js", import.meta.url), "utf8");
const appSource = await readFile(new URL("../assets/app.source.js", import.meta.url), "utf8");

const browserCore = coreSource.replace(/^export\s+/gm, "");
const browserApp = appSource.replace(/^import\s*\{[\s\S]*?\}\s*from\s*["']\.\/core\.js["'];\s*/m, "");

const banner = `/*\n * PCC Prep Assist browser bundle.\n * Generated by: npm run build\n * This classic script intentionally avoids ES-module imports so the app works\n * both on GitLab Pages and when index.html is opened directly from a ZIP.\n */\n\n`;

await writeFile(
  new URL("../assets/app.js", import.meta.url),
  `${banner}${browserCore}\n\n${browserApp}`,
  "utf8",
);
